### ISSUE TITLE
BUG: Missing dependency to typo3/testing-framework

### ISSUE THREAD

**Issue by DanielSiepmann** [sascha-egerer/phpstan-typo3#13]
The package requires `typo3/testing-framework` as dependency. Within bootstrap a class from this package is used, but no dependency is declared within `composer.json`.

Right now one has to figure that out, and require the package.

**Comment by sascha-egerer** [comment]
This is by intention because some people do not use `typo3/testing-framework` but `nimut/testing-framework`
Thats why the package `typo3/testing-framework` is suggested. See also #3 

Tell me if you have an idea how to improve this.

**Comment by DanielSiepmann** [comment]
There are ways, but I'm not sure whether they will work in this scenario.

There are virtual packages that do not exist, so one can say "Require TYPO3 Testing Framework", which is provided by `nimut/testing-framework` and `typo3/testing-framework`.

An example is `psr/log-implementation`, which is provided by Monolog.

But this has to be done within both packages + the virtual one needs to be there. But as there is no standard like PSR-x, this might not be the best idea.

Looks like I have to read suggestions more carefully ;)
