### ISSUE TITLE
Generic support for Psr\EventDispatcher\EventDispatcherInterface (psr/event-dispatcher)

### ISSUE THREAD

**Issue by bfzgaier** [sascha-egerer/phpstan-typo3#135]
Hello,

I know that psr/event-dispatcher is a 3-party dependency for TYPO3, so it is fine if it is out of scope.

Could you add generic support for `Psr\EventDispatcher\EventDispatcherInterface`.
Let's say you have code like this:
```php
$event = $eventDispatcher->dispatch(new SomeEvent());
$event->someFunction():
```
PHPStan can not resolve the real type of `$event`, therefore it will trigger an `Call to an undefined method object::someFunction()` error.

The easy solution is to add an annotation for `$event`, but you will need to do it every time you dispatch an event.
The possibility to omit the annotation would also allow for dropping the intermediate variable `$event` and combining it into one line.

Thank you for your effort and this ruleset.

**Comment by sabbelasichon** [comment]
@bfzgaier But maybe it is useful to add such a stub file in this package. I will try to discuss it with @sascha-egerer

**Comment by sabbelasichon** [comment]
@sascha-egerer What do you think? Should we add such a stub file in this package here?
