### ISSUE TITLE
Raise compatibility til php stan 0.12 

### ISSUE THREAD

**Issue by thomashohn** [sascha-egerer/phpstan-typo3#15]
Hi Sasha

Seems that phpstan-typo3 works out of the box for version 0.12 of php-stan would it be possible til raise til to that in the composer json file?

**Comment by ondrejmirtes** [comment]
There are definitely some BC breaks involved, it cannot work out of the box. But fixing them is a matter of 10 minutes and opening the project in an IDE.

**Comment by sascha-egerer** [comment]
I'm already working on it :)

**Comment by ondrejmirtes** [comment]
Be sure to check the BC breaks section in the release notes and don't hesitate to ask questions :) https://github.com/phpstan/phpstan/releases/tag/0.12.0

**Comment by sascha-egerer** [comment]
I do. And i do also have that great tool PHPStan which does also check the plugin code ;-)

**Comment by ondrejmirtes** [comment]
Awesome 😂

**Comment by sascha-egerer** [comment]
@ondrejmirtes Would be super nice if you can have a quick look...

**Comment by ondrejmirtes** [comment]
I added two comments. Otherwise looks great 👍

**Comment by sascha-egerer** [comment]
sorry have to rebase first.

**Comment by sascha-egerer** [comment]
@thomashohn Do you wan't to test the pull request? #16

**Comment by thomashohn** [comment]
I'll see if I can find the time on friday ;-)

**Comment by thomashohn** [comment]
Hi @sascha-egerer - testet it on a couple of our extensions and it seems to work ;-)
Happy weekend T
