### ISSUE TITLE
Add Support for TYPO3 v13.1

### ISSUE THREAD

**Issue by DanielSiepmann** [sascha-egerer/phpstan-typo3#159]
Hey, it would be cool if support for TYPO3 v13.1 could be added. V13.1 got released on 2024-04-23 (https://get.typo3.org/).
Right now it is not possible to install, due to version constraints on nikic/php-parser component:

```
  Problem 1
    - Root composer.json requires saschaegerer/phpstan-typo3 ^1.10 -> satisfiable by saschaegerer/phpstan-typo3[1.10.0].
    - typo3/cms-install 13.2.x-dev is an alias of typo3/cms-install dev-main and thus requires it to be installed too.
    - typo3/cms-install[dev-main, v13.1.0] require nikic/php-parser ^5.0.1 -> satisfiable by nikic/php-parser[v5.0.1, v5.0.2, 5.0.x-dev].
    - Conclusion: don't install nikic/php-parser v5.0.2 (conflict analysis result)
    - Root composer.json requires typo3/cms-install ^13.1 -> satisfiable by typo3/cms-install[v13.1.0, 13.2.x-dev (alias of dev-main)].
```

The support would allow extension developers to update their extensions, and early adopters to update their projects, while keeping phpstan working.

**Comment by sascha-egerer** [comment]
@DanielSiepmann would you like to give #160 a try?

**Comment by DanielSiepmann** [comment]
Thanks for the fast response @sascha-egerer, this seems to fix the issue within the extension https://github.com/DanielSiepmann/tracking/pull/117 as well my project setup.

**Comment by sascha-egerer** [comment]
@DanielSiepmann Just did a new release including this change.
