### ISSUE TITLE
autoloading is probably not configured properly

### ISSUE THREAD

**Issue by xbouillet** [sascha-egerer/phpstan-typo3#17]
Hello, 

I try to start with phpstan
I install phpstan like that:
  - composer install
  - composer require  saschaegerer/phpstan-typo3
  - composer require typo3/testing-framework:4.14.0
  
I execute
vendor/bin/phpstan analyse --level 0 -c phpstan.neon typo3conf/ext/myExt

It's work,  but all class in my extension was not found and that makes a lot of mistakes.

          Class myExt\Xclass\Eventnews\DayCompareViewHelper was not  
          found while trying to analyse it - autoloading is probably not     
          configured properly.   

My phpstan.neon
includes:
    - vendor/saschaegerer/phpstan-typo3/extension.neon
parameters:
    autoload_files:
        - %rootDir%/../../typo3/testing-framework/Resources/Core/Build/UnitTestsBootstrap.

Any idea please?

**Comment by ondrejmirtes** [comment]
Please follow Autoloading section in PHPStan README: https://github.com/phpstan/phpstan/blob/master/README.md

**Comment by sascha-egerer** [comment]
I'll close as it's not an issue.
