### ISSUE TITLE
Outdated MethodReflection implementation

### ISSUE THREAD

**Issue by mbrodala** [sascha-egerer/phpstan-typo3#2]
Currently this package cannot be used due to the following error:

> Fatal error: Declaration of SaschaEgerer\PhpstanTypo3\Reflection\RepositoryFindByMethodReflection::getPrototype(): PHPStan\Reflection\MethodReflection must be compatible with PHPStan\Reflection\MethodReflection::getPrototype(): PHPStan\Reflection\ClassMemberReflection in /.../vendor/saschaegerer/phpstan-typo3/src/Reflection/RepositoryFindByMethodReflection.php on line 14

See https://github.com/phpstan/phpstan/commit/8dd51d7c07def9a13004bd947a5d17ae484946a0

```
phpstan --version
PHPStan - PHP Static Analysis Tool 0.10.5
```

**Comment by sascha-egerer** [comment]
@mbrodala would be cool if you could test this version.

**Comment by mbrodala** [comment]
Looks good, the errors are gone and I can finally tackle level 2 and up. 👍

**Comment by mbrodala** [comment]
Thanks for the fix, looking forward to the next release. :-)
