### ISSUE TITLE
Handling of XClasses / registerImplementationClassName

### ISSUE THREAD

**Issue by MK-42** [sascha-egerer/phpstan-typo3#22]
Thanks for providing a phpstan extension for typo3 code!
While adopting it, I'm facing the conceptual problem of TYPO3/Extbases ability to replace implementation types dynamically at runtime.

This is especially problematic when using custom implementations for Domain-Objects (i.e. to extend a domain object of another extension) and fetching these through the original repository. phpstan then does not know that the object returned will indeed be of another type as ususal, due to the override.

For clarification a simple example:
```
namespace OtherVendor\SomeExt\Domain\Model
class Post extends AbstractEntity;

namespace OtherVendor\SomeExt\Domain\Repository
class PostRepository extends Repository;

namespace Me\Extension\Domain\Model
class SpecialPost extends \Post;

$container = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\Object\Container\Container::class);
    $container->registerImplementation(
        \OtherVendor\SomeExt\Domain\Model\Post::class,
        \Me\Extension\Domain\Model\SpecialPost::class
    );
```

when fetching `postRepository->findAll` or doing something like `blogRepository->findByPost($specialPost)` phpstan does not know the correct types.

Do you have an Idea how we could provide phpstan with that information?

**Comment by sabbelasichon** [comment]
I think that the new features called collectors can become handy here: https://phpstan.org/developing-extensions/collectors

**Comment by sabbelasichon** [comment]
@sascha-egerer  As the ObjectManager will vanish someday and i have never really had an issue with that in the wild, i would vote to close this issue.
