### ISSUE TITLE
Started to get  Could not read file GlobalDebugFunctions.php  

### ISSUE THREAD

**Issue by thomashohn** [sascha-egerer/phpstan-typo3#23]
With TYPO3 9.5.17 and phpstan > 0.12.25 I now get the following error when running php stan

Could not read file:                                                   
         /Users/path/../vendor/typo3/cms-core/Resources/PHP/GlobalDebugFunctions.php      

I'm uncertain if it's a general issue or local issue caused by the autoloader of composer? Anyone else experiencing this issue?

**Comment by sascha-egerer** [comment]
I've the same problem and i think it's related to a phpstan issue. But i could not check that yet.

**Comment by thomashohn** [comment]
It seems to occur between 0.12.25 and 0.12.6

**Comment by thomashohn** [comment]
For the moment I have created a link from typo3/sysext/core to vendor/typo3/cms-core as a temporary fix until you find time to investigate it further - seems to be some weird autoloader issue?

**Comment by thomashohn** [comment]
@sascha-egerer Seems it has been resolved with php 0.12.30 according [to](https://github.com/phpstan/phpstan/issues/3426)

**Comment by sascha-egerer** [comment]
Thank you for the update!
