### ISSUE TITLE
Do not require typo3/minimal

### ISSUE THREAD

**Issue by mbrodala** [sascha-egerer/phpstan-typo3#3]
Currently this package require `typo3/minimal` which is a metapackage pulling in various `typo3/cms-*` packages. Thus if one doesn't need all of these packages and doesn't want `typo3/minimal`, he cannot use this package.

So this package should explicitly require `typo3/cms-core` and `typo3/cms-extbase` instead.

**Comment by sascha-egerer** [comment]
@mbrodala is that change fine for you?
