### ISSUE TITLE
Add generics for Extbase Repository classes

### ISSUE THREAD

**Issue by sabbelasichon** [sascha-egerer/phpstan-typo3#31]
I am gonna try to add a PR for that

**Comment by ohader** [comment]
Seems to be related to #40

**Comment by sabbelasichon** [comment]
@ohader Yes, it is. I was talking to https://github.com/alexanderschnitzler once in a while ago and he immediately jumped on the wagon and created a standalone package for it https://github.com/alexanderschnitzler/phpstan-typo3-extbase. Which is hopefully part of this extension soon.

**Comment by sascha-egerer** [comment]
@sabbelasichon could you please give #40 a try and check if something is missing? The package of Alexander did contain some stuff that should not be required anymore at least for TYPO3 10.
So if someone is still using TYPO3 some extras stuff may be missing as i‘ve not added some stubs…
But I’m also fine with adding these stubs and maybe create a extension-typo3-9.yaml that can be loaded when required.
Does that sound like a good idea?

**Comment by sabbelasichon** [comment]
Works like a charm.
