### ISSUE TITLE
Make PHPStan aware of return type from FunctionalTestCase->get()

### ISSUE THREAD

**Issue by DanielSiepmann** [sascha-egerer/phpstan-typo3#63]
The TYPO3 Testing Framework provides a method `->get()` within `FunctionalTestCase`. This works pretty much the same as `GeneralUtility::makeInstance()`. It seems this is not yet covered by this PHPStan extension, but would be cool if it could be covered as well.

The implementation of the method can be found here: https://github.com/TYPO3/testing-framework/blob/6.16.6/Classes/Core/Functional/FunctionalTestCase.php#L487

Current workaround within tests using `phpstan/phpstan-phpunit`:
```php
$subject = $this->get(LanguageService::class);
self::assertInstanceOf(LanguageService::class, $subject);
```

**Comment by sabbelasichon** [comment]
If you use ::class everything would be fine, but some service definitions just use some arbitrary id. This could only be resolved by knowing the container definitions like in the phpstan/phpstan-symfony extension. 
I think this would be the superior solution. I have already created an issue for that: #62

**Comment by DanielSiepmann** [comment]
I use `::class` as you can see. The issue is that the phpstan extension does not add a determination for the `->get()` method of the `FunctionalTestCase`. Which I've added with the PR.

This is not about different service IDs, but adding support for this method.

**Comment by sabbelasichon** [comment]
Yeah, but behind the scene the Container is used if i know correctly.

**Comment by DanielSiepmann** [comment]
Sure. Maybe I miss something here, but phpstan doesn't recognize that, right? Otherwise, the change wouldn't be necessary.

**Comment by sabbelasichon** [comment]
No, phpstan cannot recognize it yet. But i would prefer to make it more generic so calls like GeneralUtility::getContainer()->get would also be recognized. But sure, your solution is a start to teach phpstan 95% percent of the use cases.

**Comment by DanielSiepmann** [comment]
Would also prefer a general solution, so one doesn't need to find each use case and add code for it :)

**Comment by sascha-egerer** [comment]
But is a simple class-name in and class out, isn't it? So we can simply use a stub instead and add the correct annotations instead of using a dynamicMethodReturnTypeExtension. Would be a way easier, right?

**Comment by sabbelasichon** [comment]
@sascha-egerer Maybe we should use this as a dependency to fullfill this requirement easily: https://github.com/bnf/phpstan-psr-container/blob/master/src/ContainerDynamicReturnTypeExtension.php

**Comment by sabbelasichon** [comment]
@sascha-egerer Maybe we should use this as a dependency to fullfill this requirement easily: https://github.com/bnf/phpstan-psr-container/blob/master/src/ContainerDynamicReturnTypeExtension.php

**Comment by sabbelasichon** [comment]
@sascha-egerer Maybe we should use this as a dependency to fullfill this requirement easily: https://github.com/bnf/phpstan-psr-container/blob/master/src/ContainerDynamicReturnTypeExtension.php

**Comment by bnf** [comment]
When we added `->get()` to `FunctionalTestCase` we made sure phpstan can resolve the types via https://packagist.org/packages/bnf/phpstan-psr-container –  see:
https://github.com/TYPO3/testing-framework/commit/426777c2ad280baff018c1487250a6cbcd3ba3d2
Therefor `FunctionalTestCase` started to implement the `ContainerInterface`.

We actually use this package in core since https://review.typo3.org/c/Packages/TYPO3.CMS/+/73220
So I don't see a need for `phpstan-typo3` to provide the same functionality – it could rather depend on `bnf/phpstan-psr-container` if really needed, which would help me/others in case you have improvements to the container return type extension code (It's not just used in TYPO3 context).
