### ISSUE TITLE
Also check getPropertyFromAspect in ContextAspectValidationRule

### ISSUE THREAD

**Issue by sabbelasichon** [sascha-egerer/phpstan-typo3#92]
Currently we only checking the method getAspect from the Context class. I think it would also be valuable if we check the method getPropertyFromAspect

**Comment by sascha-egerer** [comment]
Thats true but not sure how to implement. The getPropertyFromAspect method is always a custom implementation which, in most cases, does just return the same as the "get$Property" method. But it could also return something else or nothing. 
So this means we need another mapping for this in the config, right?

**Comment by sabbelasichon** [comment]
I don´t think so. The method calls hasAspect internally. If this is not the case it throws an exception.

**Comment by sabbelasichon** [comment]
So in the end the method is just a small wrapper for $this->getAspect($name)->get($property) with a default value. But if we would apply our check on the method body of getPropertyFromAspect we would complain that the given aspect does not exist.

**Comment by sascha-egerer** [comment]
A sorry i've mixed it up (i should have a look into the code before i write). What what i meant is the "get" method. This one is somehow custom code. So in the end the result of getPropertyFromAspect is also custom as it calls the get method. So it can be anything...

**Comment by sabbelasichon** [comment]
Resolved by #93
